force-app/main/default/objects/SupplierCase__c/SupplierCase__c.object-meta.xml
<CustomObject>
    <label>Supplier Case</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Ticket No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCase__c/fields/CaseType__c.field-meta.xml
<CustomField>
    <fullName>CaseType__c</fullName>
    <label>Typologie</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Faq</fullName>
                <default>true</default>
                <label>Faq</label>
            </value>
            <value>
                <fullName>Anomalie</fullName>
            </value>
            <value>
                <fullName>assistance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SupplierCase__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <label>Problématique métier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Factures</fullName>
            </value>
            <value>
                <fullName>Déclarations</fullName>
            </value>
            <value>
                <fullName>Bibliothèque</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SupplierCase__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Criticité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Faible</fullName>
                <default>true</default>
                <label>Faible</label>
            </value>
            <value>
                <fullName>Moyenne</fullName>
            </value>
            <value>
                <fullName>Forte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SupplierCase__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non traité</fullName>
                <default>true</default>
                <label>Non traité</label>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Fait</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SupplierCase__c/fields/SubmittedDate__c.field-meta.xml
<CustomField>
    <fullName>SubmittedDate__c</fullName>
    <label>Date et heure d&apos;envoi</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SupplierCase__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Titre</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Historic.cls
public with sharing class Historic {
    @AuraEnabled(cacheable=true)
    public static List<SupplierCase__c> getUserRequests() {
        String userId = UserInfo.getUserId();
        return [
            SELECT Id, Title__c, CaseType__c, Epic__c, Priority__c, Statut__c, SubmittedDate__c,Statut_Logo__c, Criticite_Logo__c, Typologie_Logo__c,Epic_Logo__c
            FROM SupplierCase__c 
            WHERE CreatedById = :userId
            ORDER BY SubmittedDate__c DESC
        ];
    }
}